services:
  ledger:
    restart: no
    container_name: ledger
    image: statuscompliance/blockchain
    privileged: true
    ports:
      - 3000:80
    volumes:
      - ./app/packages/blockchainizer/blockchain-conversion:/chaincodes
