services:
  ledger:
    restart: no
    container_name: ledger
    image: statuscompliance/blockchain
    privileged: true
    volumes:
      - ./blockchain-conversion:/chaincodes
    networks:
      - nodered_network
