services:
  ledger:
    restart: always
    container_name: ledger
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
