#FROM docker:27-dind
FROM docker:27-cli

ARG NODE_VERSION=22.11.0
ARG NPM_VERSION=10.9.1
ARG HYPERLEDGER_VERSION=2.5.10
ARG HYPERLEDGER_CA_VERSION=1.5.13
ENV DIND_DEFAULT_LABEL="dind=status-blockchain"

# Environment preparation, Node setup
COPY scripts/docker-wrapper.sh /usr/local/sbin/docker
RUN chmod 0755 /usr/local/sbin/docker && \
  apk add --no-cache nodejs~=${NODE_VERSION} npm~=${NPM_VERSION} bash && \
  apk --purge del apk-tools && \
  rm -rf /sbin/apk /etc/apk /lib/apk /usr/share/apk /var/lib/apk /bin/sh && \
  ln -s /bin/bash /bin/sh

SHELL ["/bin/bash", "-c"]
WORKDIR /app

COPY scripts/postunpack.sh /postunpack.sh
RUN mkdir -p /app/docker-images && chmod +x /postunpack.sh
